import { createHash, randomBytes } from "node:crypto";
import { sql } from "../../../../db";
import { errorResponse,requireAdmin,writeAudit } from "../../../../db/admin-auth";
import { hashPassword } from "../../../../lib/auth/password";
import { sendEmailVerification } from "../../../../lib/email";
const permissionNames=["products","orders","refunds","customers","discounts","reviews","support","content","reports"];
function hashToken(token:string){return createHash("sha256").update(token).digest("hex")}
function code(){return String(Math.floor(100000+Math.random()*900000))}
export async function GET(){try{await requireAdmin("admin_users");const[members,permissions]=await Promise.all([sql`select id,email,display_name as "displayName",role,status,two_factor_enabled as "twoFactorEnabled",created_at as "createdAt" from users where role in ('super_admin','sub_admin') and status<>'deleted' order by role desc,created_at`,sql`select user_id as "userId",permission,granted from permissions order by permission`]);return Response.json({members,permissions,permissionNames})}catch(error){return errorResponse(error)}}
export async function POST(request:Request){try{const actor=await requireAdmin("admin_users");const body=await request.json() as {email?:string;displayName?:string;password?:string;permissions?:string[]};const email=body.email?.trim().toLowerCase()??"",displayName=body.displayName?.trim()||email;if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return Response.json({error:"Enter a valid email."},{status:400});if(email===actor.email)return Response.json({error:"You cannot convert your own account."},{status:409});const existing=await sql<{id:string;role:string}[]>`select id,role from users where email=${email} limit 1`;if(existing[0]?.role==="super_admin")return Response.json({error:"A Super Admin cannot be converted."},{status:409});const passwordHash=await hashPassword(body.password??""),verificationCode=code(),token=randomBytes(32).toString("base64url");const rows=await sql<{id:string}[]>`insert into users(email,display_name,password_hash,role,status,email_verified) values(${email},${displayName},${passwordHash},'sub_admin','active',false) on conflict(email) do update set display_name=excluded.display_name,password_hash=excluded.password_hash,role='sub_admin',status='active',email_verified=false,updated_at=now() returning id`;const id=rows[0].id,granted=new Set((body.permissions??permissionNames).filter(p=>permissionNames.includes(p)));for(const permission of permissionNames)await sql`insert into permissions(user_id,permission,granted) values(${id},${permission},${granted.has(permission)}) on conflict(user_id,permission) do update set granted=excluded.granted`;await sql`delete from email_verification_tokens where user_id=${id} and used_at is null`;await sql`insert into email_verification_tokens(user_id,token_hash,code_hash,expires_at) values(${id},${hashToken(token)},${hashToken(verificationCode)},${new Date(Date.now()+10*60*1000).toISOString()})`;await sendEmailVerification({to:email,name:displayName,code:verificationCode});await writeAudit(actor,"sub_admin.create","user",id,{email,permissions:[...granted],emailVerification:"sent"});return Response.json({id,needsVerification:true,email},{status:201})}catch(error){return errorResponse(error)}}
