"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import type { CSSProperties } from "react";
import { useEffect, useMemo, useState } from "react";

type ProductStatus = "published" | "out_of_stock";
type Product = { id?:string; slug:string; name:string; type:string; price:number; status:ProductStatus; description:string };
type ApiProduct = { id:string; slug:string; name:string; description:string; productType:string; priceCents:number; currency:string; status:ProductStatus };

const serviceCatalog = [
  ["Instagram","Adobe Creative Cloud","Headspace","Picsart","n8n Starter","Surfshark VPN","ChatGPT"],
  ["Amazon Prime Video","Kling AI","QuillBot","ExpressVPN","Dreamina","Codex","Canva"],
  ["CapCut Pro","LinkedIn Career","Spotify","Apple Music","Cursor Pro","Grok",""],
  ["Claude","LinkedIn Business","Telegram Premium","Suno Premier","Perplexity Pro","HMA VPN",""],
  ["ElevenLabs","Lovable AI","YouTube Premium","Gamma Pro","HeyGen Creator","Proton VPN",""],
  ["Figma","Manus","Xbox Game Pass Ultimate","Microsoft 365","Meitu SVIP","Google AI / Gemini",""],
  ["Gmail","Netflix","Paramount+","TikTok US","Google AI Pro","Fortnite",""],
  ["Hotmail","NordVPN","Duolingo Super","Proton VPN","Adobe Full Apps","Microsoft Office 365",""],
  ["Discord Nitro","Notion","Coursera Premium","USA Virtual Phone Number","Veo 3 Ultra","",""],
  ["","OpenArt","Supabase Pro","Outlook","Antigravity","",""],
];
const categories = [...new Set(serviceCatalog.flat().filter(Boolean))];
type ServiceMeta = { color:string; logo?:string; image?:string; mark?:string; dark?:boolean };
const simpleIcon=(slug:string,color="ffffff")=>`https://cdn.simpleicons.org/${slug}/${color}`;
const favicon=(domain:string)=>`https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
const serviceMeta:Record<string,ServiceMeta> = {
  Instagram:{color:"#e4405f",logo:simpleIcon("instagram")},
  "Adobe Creative Cloud":{color:"#da1f26",image:favicon("adobe.com"),mark:"Ad"},
  Headspace:{color:"#f47d31",logo:simpleIcon("headspace")},
  Picsart:{color:"#7b61ff",logo:simpleIcon("picsart")},
  "n8n Starter":{color:"#ea4b71",logo:simpleIcon("n8n")},
  "Surfshark VPN":{color:"#17847b",logo:simpleIcon("surfshark")},
  ChatGPT:{color:"#10a37f",image:favicon("chatgpt.com"),mark:"AI"},
  "Amazon Prime Video":{color:"#00a8e1",image:favicon("primevideo.com"),mark:"Prime"},
  "Kling AI":{color:"#111827",image:favicon("klingai.com"),mark:"K"},
  QuillBot:{color:"#2f9e44",image:favicon("quillbot.com"),mark:"Q"},
  ExpressVPN:{color:"#da3940",logo:simpleIcon("expressvpn")},
  Dreamina:{color:"#4f46e5",image:favicon("dreamina.capcut.com"),mark:"D"},
  Codex:{color:"#10a37f",image:favicon("openai.com"),mark:"<>"},
  Canva:{color:"#00c4cc",image:favicon("canva.com"),mark:"C"},
  "CapCut Pro":{color:"#111827",image:favicon("capcut.com"),mark:"X"},
  "LinkedIn Career":{color:"#0a66c2",image:favicon("linkedin.com"),mark:"in"},
  Spotify:{color:"#1db954",logo:simpleIcon("spotify")},
  "Apple Music":{color:"#fa243c",logo:simpleIcon("applemusic")},
  "Cursor Pro":{color:"#111827",logo:simpleIcon("cursor")},
  Grok:{color:"#000000",logo:simpleIcon("x")},
  Claude:{color:"#d97757",logo:simpleIcon("anthropic")},
  "LinkedIn Business":{color:"#0a66c2",image:favicon("linkedin.com"),mark:"in"},
  "Telegram Premium":{color:"#26a5e4",logo:simpleIcon("telegram")},
  "Suno Premier":{color:"#7c3aed",image:favicon("suno.com"),mark:"S"},
  "Perplexity Pro":{color:"#1fb8cd",logo:simpleIcon("perplexity")},
  "HMA VPN":{color:"#7c3aed",image:favicon("hma.com"),mark:"H"},
  ElevenLabs:{color:"#111827",logo:simpleIcon("elevenlabs")},
  "Lovable AI":{color:"#ff5c8a",image:favicon("lovable.dev"),mark:"L"},
  "YouTube Premium":{color:"#ff0000",logo:simpleIcon("youtube")},
  "Gamma Pro":{color:"#7c3aed",image:favicon("gamma.app"),mark:"G"},
  "HeyGen Creator":{color:"#ec4899",image:favicon("heygen.com"),mark:"H"},
  "Proton VPN":{color:"#6d4aff",logo:simpleIcon("protonvpn")},
  Figma:{color:"#a259ff",logo:simpleIcon("figma")},
  Manus:{color:"#111827",image:favicon("manus.im"),mark:"M"},
  "Xbox Game Pass Ultimate":{color:"#107c10",image:favicon("xbox.com"),mark:"XB"},
  "Microsoft 365":{color:"#d83b01",image:favicon("microsoft365.com"),mark:"365"},
  "Meitu SVIP":{color:"#ec4899",image:favicon("meitu.com"),mark:"M"},
  "Google AI / Gemini":{color:"#4285f4",logo:simpleIcon("googlegemini")},
  Gmail:{color:"#ea4335",logo:simpleIcon("gmail")},
  Netflix:{color:"#e50914",logo:simpleIcon("netflix")},
  "Paramount+":{color:"#0064ff",logo:simpleIcon("paramountplus")},
  "TikTok US":{color:"#000000",logo:simpleIcon("tiktok")},
  "Google AI Pro":{color:"#4285f4",logo:simpleIcon("google")},
  Fortnite:{color:"#111827",logo:simpleIcon("fortnite")},
  Hotmail:{color:"#0078d4",image:favicon("outlook.live.com"),mark:"H"},
  NordVPN:{color:"#4687ff",logo:simpleIcon("nordvpn")},
  "Duolingo Super":{color:"#58cc02",logo:simpleIcon("duolingo"),dark:true},
  "Adobe Full Apps":{color:"#ff0000",image:favicon("adobe.com"),mark:"A"},
  "Microsoft Office 365":{color:"#d83b01",image:favicon("office.com"),mark:"O"},
  "Discord Nitro":{color:"#5865f2",logo:simpleIcon("discord")},
  Notion:{color:"#000000",logo:simpleIcon("notion")},
  "Coursera Premium":{color:"#0056d2",logo:simpleIcon("coursera")},
  "USA Virtual Phone Number":{color:"#2563eb",image:favicon("voice.google.com"),mark:"US"},
  "Veo 3 Ultra":{color:"#34a853",logo:simpleIcon("google")},
  OpenArt:{color:"#111827",image:favicon("openart.ai"),mark:"OA"},
  "Supabase Pro":{color:"#3ecf8e",logo:simpleIcon("supabase"),dark:true},
  Outlook:{color:"#0078d4",image:favicon("outlook.live.com"),mark:"O"},
  Antigravity:{color:"#111827",image:favicon("antigravity.google"),mark:"AG"},
};

const featured = ["Instagram","ChatGPT","Claude","YouTube Premium","Netflix","Spotify","Canva","Microsoft 365","Adobe Creative Cloud","Xbox Game Pass Ultimate","Figma","Discord Nitro","NordVPN","TikTok US"];
const money=(n:number)=>new Intl.NumberFormat("fr-MA",{style:"currency",currency:"MAD"}).format(n);
const initials=(value:string)=>value.split(/[\s/+]+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase();
const categoryTone=(value:string)=>`tone-${Math.abs([...value].reduce((sum,char)=>sum+char.charCodeAt(0),0))%8}`;
const mapProduct=(product:ApiProduct):Product=>({id:product.id,slug:product.slug,name:product.name,type:product.productType,price:product.priceCents/100,status:product.status,description:product.description});
const metaFor=(name:string)=>serviceMeta[name]??{color:"#64748b",mark:initials(name)};
function BrandLogo({name,large=false}:{name:string;large?:boolean}){const meta=metaFor(name);const symbolStyle:CSSProperties|undefined=meta.logo?{backgroundColor:meta.dark?"#101624":"#fff",WebkitMask:`url(${meta.logo}) center / contain no-repeat`,mask:`url(${meta.logo}) center / contain no-repeat`}:meta.image?{backgroundImage:`url(${meta.image})`}:undefined;return <span className={`brand-logo ${large?"large":""} ${meta.image?"has-image":""}`} style={{"--brand":meta.color} as CSSProperties} aria-hidden="true"><span className="brand-symbol" style={symbolStyle}>{meta.logo||meta.image?"":meta.mark}</span></span>}

function Mark(){return <Link className="mark" href="/" prefetch aria-label="Accueil Nexora"><span>N</span>Nexora</Link>}
function CartIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.2 6h15l-1.7 8.2H8.1L6.2 3H3"/><circle cx="9.2" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/></svg>}

function Header({cart,onTheme}:{cart:number;onTheme:()=>void}){const[open,setOpen]=useState(false);return <header className="site-header market-header"><div className="nav-wrap"><div className="brand-zone"><Mark/><span>Digital products store</span></div><button className="mobile-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}>Menu</button><nav className={open?"nav open":"nav"}><a href="/#choose">Choose your product</a><Link href="/products" prefetch>All products</Link><Link href="/contact" prefetch>Support</Link></nav><div className="header-actions"><button className="icon-btn theme-toggle" onClick={onTheme} aria-label="Changer le thème">◐</button><Link className="cart-btn" href="/cart" prefetch aria-label={`Panier avec ${cart} articles`}><CartIcon/><span>Panier</span><b>{cart}</b></Link></div></div></header>}

function Hero(){return <section className="hero market-hero"><div className="hero-copy"><div className="eyebrow"><span/> Instant digital access</div><h1>All your digital products, in one clean place.</h1><p>Subscriptions, AI tools, creative apps, VPNs, gaming codes, streaming services and productivity accounts, sold clearly in MAD with checkout by email.</p><div className="hero-actions"><a className="button primary" href="#choose">Choose your product</a><a className="text-link" href="/products">Browse all</a></div><div className="hero-proof"><div><b>50+</b><span>digital categories</span></div><div><b>MAD</b><span>local pricing</span></div><div><b>Email</b><span>simple orders</span></div></div></div><div className="digital-wall" aria-hidden="true">{featured.map((name,index)=><span key={name} style={{"--brand":metaFor(name).color,animationDelay:`${index*110}ms`} as CSSProperties}><BrandLogo name={name}/>{name}</span>)}</div></section>}

function CategoryGrid(){return <section className="category-hub" id="choose"><div className="section-head"><div><span className="overline">Choose your product</span><h2>Pick a category.</h2></div></div><div className="service-table" role="list">{categories.map((name,index)=><a role="listitem" className="service-button" style={{"--brand":metaFor(name).color,animationDelay:`${index*20}ms`} as CSSProperties} href={`/products?category=${encodeURIComponent(name)}`} key={name}><BrandLogo name={name}/><span>{name}</span></a>)}</div></section>}

function ProductArt({product,large=false}:{product:Product;large?:boolean}){return <div className={`product-art universal-card ${categoryTone(product.type)} ${large?"large":""}`} style={{"--brand":metaFor(product.type).color} as CSSProperties}><div className="platform-card"><div className="platform-top"><span>{product.type}</span><b>DIGITAL</b></div><div className="product-brand"><BrandLogo name={product.type} large/><strong>{initials(product.type)}</strong></div><em>{product.name}</em><div className="code-strip"><span>CODE</span><i>READY BY EMAIL</i></div></div><span className="art-kicker">{product.status==="out_of_stock"?"Out of stock":product.type}</span><span className="art-index">{money(product.price)}</span></div>}
function ProductCard({product,onAdd}:{product:Product;onAdd:(p:Product)=>void}){const disabled=product.status==="out_of_stock";return <article className={`product-card ${disabled?"is-out":""}`}><Link href={`/products/${product.slug}`} prefetch className="art-link"><ProductArt product={product}/><span className="badge">{disabled?"Stock out":"Available"}</span></Link><div className="product-info"><div><p>{product.type}</p><h3><Link href={`/products/${product.slug}`} prefetch>{product.name}</Link></h3></div><div className="price">{money(product.price)}</div></div><div className="card-foot"><span>{disabled?"Temporarily unavailable":"Digital delivery"}</span><button disabled={disabled} onClick={()=>onAdd(product)}>{disabled?"Indisponible":"Ajouter +"}</button></div></article>}

function Home({products,onAdd}:{products:Product[];onAdd:(p:Product)=>void}){return <main><Hero/><CategoryGrid/>{products.length?<section className="section"><div className="section-head"><div><span className="overline">Latest products</span><h2>Available now.</h2></div><a href="/products">All products</a></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.slug} product={p} onAdd={onAdd}/>)}</div></section>:<section className="all-products-cta"><div><span className="overline">Full catalogue</span><h2>Ready when you add products.</h2><p>Open the complete catalogue or add new products from admin; every category button already filters the storefront.</p></div><a className="button primary" href="/products">All products</a></section>}<section className="benefits">{[["01","Wide catalogue","AI, design, VPN, streaming, gaming and productivity products in one store."],["02","Simple checkout","Clients order with email only, no customer account needed."],["03","Clear availability","Admins can mark any product as out of stock instantly."],["04","Direct support","Every message goes to your admin contact workflow."]].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</section><Newsletter/></main>}

function Catalog({products,onAdd}:{products:Product[];onAdd:(p:Product)=>void}){const searchParams=useSearchParams();const[q,setQ]=useState("");const[sort,setSort]=useState("popular");const[view,setView]=useState("grid");const[selectedCategories,setSelectedCategories]=useState<string[]>([]);useEffect(()=>{const category=searchParams.get("category");setSelectedCategories(category&&categories.includes(category)?[category]:[])},[searchParams]);const toggle=(value:string)=>setSelectedCategories(list=>list.includes(value)?list.filter(item=>item!==value):[...list,value]);const clear=()=>{setQ("");setSort("popular");setSelectedCategories([])};const shown=useMemo(()=>[...products].filter(p=>{const text=(p.name+p.type+p.description).toLowerCase();return text.includes(q.toLowerCase())&&(!selectedCategories.length||selectedCategories.includes(p.type))}).sort((a,b)=>sort==="price"?a.price-b.price:sort==="name"?a.name.localeCompare(b.name):a.status.localeCompare(b.status)),[products,q,sort,selectedCategories]);return <main className="page"><div className="page-title"><span className="overline">Products</span><h1>Choose the digital product you need.</h1><p>Filter by category, search by product name, then add available products to the cart.</p></div><div className="catalog-tools"><label className="search">⌕ <input aria-label="Rechercher" placeholder="Search product" value={q} onChange={e=>setQ(e.target.value)}/></label><div><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Availability</option><option value="name">Name</option><option value="price">Price</option></select></label><button onClick={()=>setView(view==="grid"?"list":"grid")}>{view==="grid"?"List":"Grid"}</button><button onClick={clear}>Reset</button></div></div><div className="catalog-layout"><aside><b>Categories</b><label><input type="checkbox" checked={!selectedCategories.length} onChange={()=>setSelectedCategories([])}/><span>All</span></label>{categories.map(x=><label key={x}><input type="checkbox" checked={selectedCategories.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</aside><section><div className="result-count">{shown.length} products <span>{selectedCategories.length?"Filtered":"Admin catalogue"}</span></div>{shown.length?<div className={`product-grid ${view}`}>{shown.map(p=><ProductCard key={p.slug} product={p} onAdd={onAdd}/>)}</div>:<div className="empty"><h2>No product found.</h2><p>Add products from admin or choose another category.</p><button className="button primary" onClick={clear}>Reset</button></div>}</section></div></main>}

function ProductDetail({products,slug,onAdd}:{products:Product[];slug:string;onAdd:(p:Product)=>void}){const p=products.find(x=>x.slug===slug);if(!p)return <Status title="Product unavailable." text="This product is not available right now."/>;const disabled=p.status==="out_of_stock";return <main className="page product-page"><div className="breadcrumbs"><a href="/">Home</a> / <a href="/products">Products</a> / {p.name}</div><section className="product-detail"><div><ProductArt product={p} large/></div><div className="buy-panel"><span className="badge inline">{disabled?"Out of stock":"Available"}</span><p className="overline">{p.type}</p><h1>{p.name}</h1><p className="lead">{p.description}</p><ul><li>Digital product managed by admin</li><li>Checkout by email, no client account</li><li>Support available after purchase</li></ul><button className="button primary wide" disabled={disabled} onClick={()=>onAdd(p)}>{disabled?"Out of stock":`Add to cart - ${money(p.price)}`}</button><a className={`button outline wide ${disabled?"disabled":""}`} href="/checkout">Buy now</a><div className="secure-note">Secure checkout · Prices in MAD · Email delivery workflow</div></div></section></main>}

function Cart({items,onRemove}:{items:Product[];onRemove:(i:number)=>void}){const total=items.reduce((s,p)=>s+p.price,0);return <main className="page compact"><div className="page-title small"><span className="overline">Cart</span><h1>Your cart.</h1><p>{items.length} digital product{items.length>1?"s":""}.</p></div><div className="cart-layout"><section>{items.length?items.map((p,i)=><article className="cart-line" key={`${p.slug}-${i}`}><ProductArt product={p}/><div><p>{p.type}</p><h3>{p.name}</h3><span>Digital product</span><button onClick={()=>onRemove(i)}>Remove</button></div><strong>{money(p.price)}</strong></article>):<div className="empty"><h2>Your cart is empty.</h2><p>Choose a digital product to continue.</p><a className="button primary" href="/products">See products</a></div>}</section><aside className="summary"><h2>Summary</h2><p><span>Subtotal</span><b>{money(total)}</b></p><p><span>Currency</span><b>MAD</b></p><hr/><p className="total"><span>Total</span><b>{money(total)}</b></p><a className={`button primary wide ${!items.length?"disabled":""}`} href={items.length?"/checkout":"#"}>Continue to payment</a><small>Payment through Stripe Checkout.</small></aside></div></main>}

function Checkout({items}:{items:Product[]}){const[busy,setBusy]=useState(false);const[error,setError]=useState("");const total=items.reduce((s,p)=>s+p.price,0);async function pay(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!items.length)return;setBusy(true);setError("");const form=new FormData(e.currentTarget);try{const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),items:items.map(p=>({slug:p.slug,quantity:1}))})});const result=await response.json() as {checkoutUrl?:string;error?:string};if(!response.ok||!result.checkoutUrl)throw new Error(result.error||"Payment unavailable.");window.location.assign(result.checkoutUrl)}catch(cause){setError(cause instanceof Error?cause.message:"Payment unavailable.");setBusy(false)}}if(!items.length)return <Status title="Empty cart." text="Add an available product before checkout."/>;return <main className="checkout"><div className="checkout-head"><Mark/><span>Secure payment</span></div><div className="checkout-grid"><form onSubmit={pay}><a href="/cart">Back to cart</a><h1>Complete your order.</h1><p>The product is attached to the email you enter here.</p><h2>1. Contact</h2><label>Email<input required name="email" type="email" placeholder="you@email.com"/></label><h2>2. Information</h2><div className="form-grid"><label>Full name<input required placeholder="Nizar Elkarni"/></label><label>Country<select><option>Morocco</option><option>France</option><option>Belgium</option></select></label></div><h2>3. Payment</h2><div className="hosted-field">You will continue to a secure payment page.</div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary wide" disabled={busy}>{busy?"Opening payment...":`Pay ${money(total)}`}</button></form><aside><h2>Your order</h2>{items.map((p,i)=><div className="mini-line" key={i}><ProductArt product={p}/><span><b>{p.name}</b><small>{p.type}</small></span><strong>{money(p.price)}</strong></div>)}<p><span>Subtotal</span><b>{money(total)}</b></p><hr/><p className="total"><span>Total</span><b>{money(total)}</b></p><div className="trust">Protected payment<br/><small>No card number stored by Nexora</small></div></aside></div></main>}

function ContactPage(){const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=new FormData(e.currentTarget);const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});setMessage(response.ok?"Message sent. We will reply by email.":"Could not send the message.");setBusy(false);if(response.ok)e.currentTarget.reset()}return <main className="page policy"><span className="overline">Contact</span><h1>Need help with a digital product?</h1><p>Send the product name, your email, and what you need. Your message stays visible in the administration.</p><form className="auth-form" onSubmit={submit}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Subject<input name="subject" required/></label><label>Message<textarea name="message" required minLength={10}/></label>{message&&<div className="admin-alert">{message}</div>}<button className="button primary wide" disabled={busy}>{busy?"Sending...":"Send"}</button></form></main>}

function Policy({route}:{route:string}){const titles:Record<string,string>={about:"About Nexora",faq:"Questions",terms:"Terms",privacy:"Privacy","cookie-policy":"Cookies","refund-policy":"Refunds","license-policy":"Digital product terms"};if(route==="contact")return <ContactPage/>;return <main className="page policy"><span className="overline">NEXORA</span><h1>{titles[route]||"Page not found"}</h1>{titles[route]?<><p className="updated">Updated September 5, 2026</p><h2>Digital products marketplace.</h2><p>Nexora sells digital subscriptions, apps, accounts, codes, and services with clear prices in MAD.</p><h2>Payment and delivery</h2><p>Payment runs through Stripe Checkout. Orders are handled with the email used during payment.</p><h2>Support</h2><p>Contact us through the support page for any product question.</p></>:<Status title="Page not found." text="The address may be incorrect."/>}</main>}
function Status({title,text}:{title:string;text:string}){return <main className="status-page"><span>NEXORA</span><h1>{title}</h1><p>{text}</p><a href="/" className="button primary">Back to store</a></main>}
function Newsletter(){const[msg,setMsg]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const response=await fetch("/api/newsletter",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email")})});setMsg(response.ok?"Subscription saved.":"Invalid email.");if(response.ok)e.currentTarget.reset()}return <section className="newsletter"><div><span className="overline">Newsletter</span><h2>New digital products first.</h2><p>Get updates when new tools, subscriptions, and offers are added.</p></div><form onSubmit={submit}><label><span className="sr-only">Email</span><input name="email" type="email" required placeholder="you@email.com"/><button>Subscribe</button></label>{msg&&<small>{msg}</small>}</form></section>}
function Footer(){return <footer className="footer"><div><Mark/><p>Digital subscriptions, creative tools, AI apps, VPNs, streaming and gaming products.</p></div><div><b>Store</b><a href="/products">Products</a><a href="/#choose">Categories</a><a href="/cart">Cart</a></div><div><b>Help</b><a href="/contact">Contact</a><a href="/faq">FAQ</a><a href="mailto:Nizarelkarni@gmail.com">Email</a></div><div><b>Legal</b><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/refund-policy">Refunds</a></div><small>© 2026 Nexora Market.</small></footer>}

export function Storefront({route}:{route:string}){const[products,setProducts]=useState<Product[]>([]);const[items,setItems]=useState<Product[]>([]);const[toast,setToast]=useState("");useEffect(()=>{document.documentElement.dataset.theme=localStorage.getItem("theme")||"light";fetch("/api/products").then(r=>r.json()).then((body:{products?:ApiProduct[]})=>setProducts((body.products??[]).map(mapProduct))).catch(()=>setProducts([]))},[]);const add=(p:Product)=>{if(p.status==="out_of_stock")return;setItems(v=>[...v,p]);setToast(`${p.name} added to cart`);setTimeout(()=>setToast(""),2600)};const theme=()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("theme",next)};const plain=route==="checkout"||route==="account"||route==="admin";let content:React.ReactNode;if(route==="home")content=<Home products={products} onAdd={add}/>;else if(route==="products")content=<Catalog products={products} onAdd={add}/>;else if(route.startsWith("products/"))content=<ProductDetail products={products} slug={route.split("/")[1]} onAdd={add}/>;else if(route==="cart")content=<Cart items={items} onRemove={i=>setItems(v=>v.filter((_,n)=>n!==i))}/>;else if(route==="checkout")content=<Checkout items={items}/>;else if(route==="account")content=<Status title="Client accounts are disabled." text="Clients order by email without creating an account."/>;else if(["payment/success","payment/pending","payment/failed","payment/canceled"].includes(route))content=<Status title={route.endsWith("success")?"Payment confirmed.":route.endsWith("pending")?"Payment pending.":"Payment not completed."} text="We will process your order after payment confirmation."/>;else content=<Policy route={route}/>;return <>{!plain&&<Header cart={items.length} onTheme={theme}/>} {content} {!plain&&<Footer/>} {toast&&<div className="toast" role="status">✓ {toast}<a href="/cart">View cart</a></div>}</>}
